# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=30)),
                ('description', models.TextField(default='Discipline')),
                ('registration_date', models.DateField(default=datetime.date(2017, 4, 20))),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('description', models.TextField(default='Hard working')),
                ('registration_date', models.DateField(default=datetime.date(2017, 1, 1))),
                ('graduation_date', models.DateField(default=datetime.date(2017, 1, 1))),
            ],
        ),
    ]
